---
booktitle: 'Proceedings of the Tenth International Symposium on Imprecise Probability:
  Theories and Applications'
shortname: ISIPTA '17
year: '2017'
start: 2017-07-10
end: 2017-07-14
published: 2017-06-20
url: http://proceedings.mlr.press
location: Lugano, Switzerland
volume: 62
layout: proceedings
series: Proceedings of Machine Learning Research
id: isipta17
month: 0
cycles: false
editor:
- given: Alessandro
  family: Antonucci
- given: Giorgio
  family: Corani
- given: Inés
  family: Couso
- given: Sébastien
  family: Destercke
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Tenth International Symposium on Imprecise Probability: Theories and Applications on 10-14 July 2017

  Published as Volume 62 by the Proceedings of Machine Learning Research on 20 June 2017.

  Volume Edited by:
    Alessandro Antonucci
    Giorgio Corani
    Inés Couso
    Sébastien Destercke

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 10--14 Jul
baseurl: "/v62"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v62
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: 'Proceedings of the Tenth International Symposium on Imprecise Probability:
    Theories and Applications'
  url: 
  location: 
  dates:
  - 2017-07-10
  - 2017-07-11
  - 2017-07-12
  - 2017-07-13
  - 2017-07-14
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from /Users/mreid/mlresearch/v62/isipta17.bib
